### ISSUE TITLE
expm.co leading to dodgy site

### ISSUE THREAD

**Issue by bigos** [lfe/quick-start#1]
https://github.com/lfe/quick-start/blob/master/2.md

section 2.2

Perhaps expm.co was hacked?

**Comment by oubiwann** [comment]
Oh, man. Looks like the Elixir community got rid of that archive. So much for maintaining backwards compatibility!

**Comment by oubiwann** [comment]
I can't even find any recent information with a quick google :-/ hex.pm is certainly the successor, but I believe it requires both the use of the Elxir `mix` tool, their `hex` tool, and the installation of Elixir itself. Far too heavy for our needs.

I guess I'll just pull the `expm` stuff out of lfetool and remove the link from the quick start.

Thanks!

**Comment by oubiwann** [comment]
This has been addressed now.
